baseurl: "https://imxie.itscoder.com"
languageCode: "zh-cn"
title: "IMXIE"
theme: "hugo-tania"
paginate: 100

disqusShortname: 

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  # siteName: "IMXIE"
  # siteDesc: "IMXIE"
  author: "Hugo"


  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  mainSections:
    - posts

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to: 
    email: Hugo3641@gmail.com
    facebook:
    github: https://github.com/xcc3641
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram: https://t.me/guangzhibu2
    twitter:
    twitch:
    whatsapp:
    z-app-store: https://apps.apple.com/us/developer/%E6%99%A8%E6%88%90-%E8%B0%A2/id1552871946
    z-google-play: https://play.google.com/store/apps/dev?id=6600056662611762016
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: 我的作品
      url: "/app"
    - name: 日志
      url: "/articles/"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
