baseurl: "https://imxie.itscoder.com"
languageCode: "zh-cn"
title: ""
theme: "hugo-tania"
paginate: 100

disqusShortname: 

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: favicon.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "IMXIE"
  # siteDesc: "Hugo is Absurdly Fast!"
  author: "Hugo"


  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  mainSections:
    - posts

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to: 
    email: Hugo3641@gmail.com
    facebook:
    github: https://github.com/xcc3641
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram: https://t.me/guangzhibu2
    twitter:
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: Articles
      url: "/articles/"
  # footer:
  #   - name: RSS
  #     url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
